#!/bin/bash
# Build T-Minus.app as a universal binary (Apple Silicon + Intel).
#   ./build.sh            build only
#   ./build.sh --install  copy to ~/Applications and launch
#   ./build.sh --dist     also produce build/T-Minus.dmg (drag-to-install) and build/T-Minus.zip
set -euo pipefail
cd "$(dirname "$0")"

APP="build/T-Minus.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" build/obj

for arch in arm64 x86_64; do
  swiftc -O -swift-version 5 \
    -target "$arch-apple-macos14.0" \
    Sources/*.swift \
    -o "build/obj/TMinus-$arch"
done
lipo -create build/obj/TMinus-arm64 build/obj/TMinus-x86_64 -output "$APP/Contents/MacOS/TMinus"

cp Info.plist "$APP/Contents/"
# The icon is generated by Icon/make_icon.swift; re-run that after changing the artwork.
cp Icon/AppIcon.icns "$APP/Contents/Resources/"
codesign --force --sign - "$APP"
echo "✓ built $APP ($(lipo -archs "$APP/Contents/MacOS/TMinus"))"

case "${1:-}" in
  --install)
    pkill -x TMinus 2>/dev/null || true
    mkdir -p ~/Applications
    rm -rf ~/Applications/T-Minus.app
    cp -R "$APP" ~/Applications/
    open ~/Applications/T-Minus.app
    echo "✓ installed to ~/Applications/T-Minus.app (look at your menu bar)"
    ;;
  --dist)
    rm -f build/T-Minus.zip
    ditto -c -k --keepParent "$APP" build/T-Minus.zip
    echo "✓ packaged build/T-Minus.zip"

    # Disk image: the app, an Applications shortcut to drag it onto, a background and a volume icon.
    VOL="T-Minus"
    STAGE="build/dmg"
    rm -rf "$STAGE" build/T-Minus.dmg build/rw.dmg
    mkdir -p "$STAGE/.background"
    cp -R "$APP" "$STAGE/"
    ln -s /Applications "$STAGE/Applications"
    swift Icon/make_dmg_background.swift "$STAGE/.background/background.tiff" >/dev/null

    # A leftover "T-Minus" disk (an old build or test mount) would make the new one mount as
    # "T-Minus 1" and Finder would lay out the wrong window, so eject it first.
    hdiutil detach "/Volumes/$VOL" -force -quiet 2>/dev/null || true
    if [ -e "/Volumes/$VOL" ]; then
      echo "✗ a \"$VOL\" disk is still mounted (is T-Minus running from it?). Eject it and retry." >&2
      exit 1
    fi
    # Leave headroom for the volume icon and Finder's layout file, added after creation.
    SIZE_MB=$(( $(du -sm "$STAGE" | cut -f1) + 20 ))
    hdiutil create -quiet -srcfolder "$STAGE" -volname "$VOL" -fs HFS+ -format UDRW -size "${SIZE_MB}m" -ov build/rw.dmg
    ATTACH=$(hdiutil attach -readwrite -noverify -noautoopen build/rw.dmg 2>/dev/null)
    DEV=$(echo "$ATTACH" | awk '/Apple_HFS/ {print $1}')
    MNT=$(echo "$ATTACH" | awk -F'\t' '/Apple_HFS/ {print $NF}')
    trap 'hdiutil detach "$DEV" -force -quiet 2>/dev/null || true' EXIT
    # Lay out the Finder window. Needs Finder automation permission; the image still works without it.
    osascript <<EOF || echo "  (skipped window layout — allow Terminal to control Finder to get it)"
tell application "Finder"
  tell disk "$VOL"
    open
    set current view of container window to icon view
    set toolbar visible of container window to false
    set statusbar visible of container window to false
    set the bounds of container window to {200, 120, 840, 548}
    set opts to the icon view options of container window
    set arrangement of opts to not arranged
    set icon size of opts to 128
    set text size of opts to 13
    set background picture of opts to file ".background:background.tiff"
    set position of item "T-Minus.app" of container window to {160, 190}
    set position of item "Applications" of container window to {480, 190}
    update without registering applications
    delay 1
    close
  end tell
end tell
EOF
    # Finder writes the layout (.DS_Store) shortly after closing the window; wait for it.
    for _ in 1 2 3 4 5 6 7 8 9 10; do [ -f "$MNT/.DS_Store" ] && break; sleep 0.5; done
    # Volume icon goes in last: hdiutil -srcfolder skips .VolumeIcon.icns, and Finder deletes it
    # while saving the window layout above.
    cp Icon/AppIcon.icns "$MNT/.VolumeIcon.icns"
    SetFile -a C "$MNT"
    rm -rf "$MNT/.fseventsd"
    sync
    # Spotlight or Finder can hold the disk for a moment; retry before forcing.
    for _ in 1 2 3 4 5; do hdiutil detach "$DEV" -quiet 2>/dev/null && break; sleep 1; done
    hdiutil detach "$DEV" -force -quiet 2>/dev/null || true
    trap - EXIT
    hdiutil convert -quiet build/rw.dmg -format UDZO -imagekey zlib-level=9 -o build/T-Minus.dmg
    rm -rf build/rw.dmg "$STAGE"
    codesign --force --sign - build/T-Minus.dmg
    echo "✓ packaged build/T-Minus.dmg"
    ;;
esac
